// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class DeliveryBatch
{
    private DeliveryBatch()
    {
        DeliveryBatchContents = new List<DeliveryBatchContent>();
    }

    public int DeliveryBatchId { get; private set; }

    public DateTime? Date { get; private set; }

    public ICollection<DeliveryBatchContent> DeliveryBatchContents { get; private set; }
}