// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain;
using System;
using System.Collections.Generic;

namespace Domain;

public class LocationType
{
    private LocationType()
    {
        Locations = new List<Location>();
    }

    public int LocationTypeId { get; private set; }

    public string LocationType1 { get; private set; }

    public virtual ICollection<Location> Locations { get; private set; }
}