// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class Location
{
    private Location()
    {
        ProductGroups = new List<ProductGroup>();
    }

    public int LocationId { get; private set; }

    public string Code { get; private set; }

    public int? LocationTypeId { get; private set; }

    public virtual LocationType LocationType { get; private set; }

    public virtual ICollection<ProductGroup> ProductGroups { get; private set; }
}