// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class ProductGroupContent
{
    private ProductGroupContent() { }

    public int ProductGroupId { get; private set; }

    public int ProductId { get; private set; }

    public int DeliveryBatchId { get; private set; }

    public int? Quantity { get; private set; }

    public virtual DeliveryBatchContent DeliveryBatchContent { get; private set; }

    public virtual ProductGroup ProductGroup { get; private set; }
}