// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class ProductGroup
{
    private ProductGroup()
    {
        ProductGroupContents = new List<ProductGroupContent>();
    }

    public void ChangeLocation(Location location)
    {
        Location = location;
    }

    public int ProductGroupId { get; private set; }

    public int? LocationId { get; private set; }

    public Location Location { get; private set; }

    public ICollection<ProductGroupContent> ProductGroupContents { get; private set; } 
}