// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class ProductGroupContent
{
    private ProductGroupContent() { }

    public ProductGroupContent(int productGroupId, int productId, int deliveryBtachId, int quantity) : this()
    {
        ProductGroupId = productGroupId;
        ProductId = productId;
        DeliveryBatchId = deliveryBtachId;
        Quantity = quantity;
    }

    public ProductGroupContent MoveProductGroupContent(Location newLocation, int quantityToMove)
    {
        ProductGroup newProductGroup = newLocation.ProductGroup ?? newLocation.CreateProductGroup();

        if (quantityToMove > Quantity)
        {
            throw new Exception("Insufficient quantity");
        }
        else
        {
            Quantity -= quantityToMove;
            return newProductGroup.AddProductGroupContent(ProductId, DeliveryBatchId, quantityToMove);
        }
    }

    public void AddQuantity(int quantity)
    {
        Quantity += quantity;
    }

    public int ProductGroupId { get; private set; }

    public int ProductId { get; private set; }

    public int DeliveryBatchId { get; private set; }

    public int? Quantity { get; private set; }

    public DeliveryBatchContent DeliveryBatchContent { get; private set; }

    public ProductGroup ProductGroup { get; private set; }
}