// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain;

public class Product
{
    private Product()
    {
        DeliveryBatchContents = new List<DeliveryBatchContent>();
        Locations = new List<Location>();
    }

    public int ProductId { get; private set; }

    public string Name { get; private set; }

    public ICollection<DeliveryBatchContent> DeliveryBatchContents { get; private set; }

    public ICollection<Location> Locations { get; private set; }
}